### ISSUE TITLE
유저 정보 확인 불가에 따른 이슈

### ISSUE THREAD

**Issue by syhan7516** [KumohTaxi/Frontend#3]
1. 참가자 채팅 불가
2. 마이그룹에서 그룹 정보 확인 불가
3. 기존 채팅 조회 & 전송 불가
4. 그룹 나가기 및 방 만들기, 참여 불가
 detailed issue
  - 참가자 : 시간 내 그룹에서 모든 기능 사용 제약 & 시간 초과 그룹에서 첫 참여 성공하나, 그 다음 모든 기능 사용 제약
  - 캡틴 : 시간 내 그룹 관련 기능은 다 가능 & 시간 초과 그룹에서 모든 기능 사용 제약

**Comment by star-sil** [comment]
시간 초과되면 자동으로 그룹에서 나감 처리되지 않나요?
유저 정보는 왜 확인 불가능하다는 건가요?

**Comment by syhan7516** [comment]
> 시간 초과되면 자동으로 그룹에서 나감 처리되지 않나요? 유저 정보는 왜 확인 불가능하다는 건가요?

최근에 전첵적으로 확인해본 결과 자동으로 그룹에서 나가지지않은 것을 확인했습니다.

구체적인 내용은 그룹에서는 나가졌으나, 그 상태에서 다른 그룹을 참여하려고할 때 이미 참여한 그룹이있다고 알림창이 뜹니다.

**Comment by star-sil** [comment]
> 최근에 전체적으로 확인해본 결과 자동으로 그룹에서 나가지지않은 것을 확인했습니다.
> 
> 구체적인 내용은 화면상으로는 그룹에서는 나가졌으나, 그 상태에서 다른 그룹을 참여하려고할 때 이미 참여한 그룹이있다고 알림창이 뜹니다.

아하 그럼 백엔드 쪽에 문제가 있는 것 같네요 한번 확인해보겠습니다.

**Comment by star-sil** [comment]
프론트에서 요청한 api 결과를 확인할 수 있을까요?

**Comment by syhan7516** [comment]
> 프론트에서 요청한 api 결과를 확인할 수 있을까요? 
 
그룹 만들기를 진행해주시면 해당 사항 진행하도록하겠습니다.

**Comment by star-sil** [comment]
> 현재 캡틴관련 기능 이슈는 해결이 완료된 상태이고,
> 
> 그 외 참가자의 이슈는 그룹 만들기를 진행해주시면 해당 사항에 대한 api 결과를 보고드리도록 하겠습니다.

넵 감사합니다

**Comment by syhan7516** [comment]
참가자 이슈
1. 참가자 채팅 불가
2. 마이그룹에서 그룹 정보 확인 불가
3. 기존 채팅 조회 & 전송 불가
4. 그룹 나가기 및 방 만들기, 참여 불가

참가자 이슈관련 문제는 참가자에 대한 id관련 등 여러 데이터가 방장일 때 경우에만 조건이 적용이된 것이 원인이었습니다.
방장일 때만 적용되던 범위를 일반 참가자까지 범위를 넒혀 해결하였습니다.

**Comment by GHWooo** [comment]
확인 후 코드 수정했습니다.
