### ISSUE TITLE
방장 & 사용자 그룹 데이터 이슈

### ISSUE THREAD

**Issue by syhan7516** [KumohTaxi/Frontend#4]
## 개요
 방장 & 사용자의 그룹 데이터 삭제 후 새로고침 시 그룹 데이터가 없음.

## 상세내용
 방장 & 사용자의 그룹 데이터 삭제 후 새로고침을 하면 로그인 초기화면으로 돌아감. ( 토큰 정보가 사라져 맞는 결과 )
 로그인 후 기존의 그룹 데이터 정보로 방 참여 여부를 확인하여야하는데, 그룹 데이터가 없음. ( 토큰 및 다른 데이터는 모두 존재 )
 그 결과 다른 방의 참여가 가능해지며, 참여하면서 해당 방의 그룹 데이터를 받아옴. ( 하지만 방 생성은 불가능 ! )

**Comment by syhan7516** [comment]
방장 & 사용자 그룹 데이터 이슈

- 문제 1
 : 로그인 후 기존의 그룹 데이터 정보로 방 참여 여부를 확인하여야하는데, 그룹 데이터가 없어서 관련 기능들이 문제 발생
- 원인 : 토큰 및 다른 데이터는 모두 존재하나, 나의 그룹 데이터가 없는 것이 원인

- 문제 2
:  그 결과 방 생성은 불가능 하지만 다른 방의 참여가 가능해지며, 참여하면서 해당 방의 그룹 데이터를 받아와지는 문제 발생
- 원인 : 나의 그룹 데이터가 없는 것으로 문제1의 원인과 동일

- 해결 
 : 서버 쪽으로 그룹 데이터를 받아오는 조건이 문제 발생의 원인이었고, 그룹 데이터를 무조건적으로 요청은 하되, 그 값이 있다면 데이터가 적용 환경을 만들고, 없다면 없을 때의 환경으로 적용시키는 것으로 해결

- 수정 파일된 파일 : Navbar 
-  파일 내 코드 변경 내용 : Navbar의 useEffect 내 if 조건문 삭제

- 코드 파일 업로드 : [issue_code.zip](https://github.com/KumohTaxi/Frontend/files/9593252/issue_code.zip)

**Comment by GHWooo** [comment]
코드 수정했습니다.
