### ISSUE TITLE
로그인 없이 메인페이지 접근허용

### ISSUE THREAD

**Issue by star-sil** [KumohTaxi/Frontend#5]
## 개요
현재 서비스는 로그인을 해야 메인페이지에 접근이 가능하다. 하지만 이러한 방식은 접근성이 떨어져 사용자가 이용에 불편을 느낄 수 있다.

## 해결방안
로그인 없이 메인메이지에 접근할 수 있도록하고 로그인이 필요한 기능은 해당 기능을 사용할시 로그인을 하도록 유도하기

**Comment by GHWooo** [comment]
It was solved by implementing the integrated main page.
