### ISSUE TITLE
Firebase chatting issue

### ISSUE THREAD

**Issue by syhan7516** [KumohTaxi/Frontend#7]
### 개요 <hr>
 : Firebase chatting issue

### 상세내용 <hr>
 : 채팅방에 들어가면 채팅 화면 자체가 띄워지지 않으며, 당연히 채팅도 불가한 이슈 발생

### Issue File <hr>

-  firebaseInfo.js
- BSDChatRoomPage.js

**Comment by syhan7516** [comment]
### 문제 <hr>
 : 채팅방에 들어가면 채팅 화면 자체가 띄워지지 않으며, 당연히 채팅도 불가한 이슈 발생
### 원인 <hr>
 : 채팅 전송 시 전달되는 데이터 형식 오류로 해당 채팅 데이터를 불러와 화면에 띄우는 것이 불가능
### 해결 <hr>
 : 채팅 전송 시 전달되는 데이터 형식과 FIrebase chatting 데이터 형식 일치시키기 
### Modified File <hr>

- firebaseInfo.js
- BSDChatRoomPage.js

### Modified Code In File <hr>
- firebaseInfo.js : Firebase initialize 및 Firestore define 코드 재작성
- BSDChatRoomPage.js : 채팅 전달 객체 데이터 형식 이름, 내용, 날짜로 구성

### Upload Code File <hr>
: [Troubleshooting.zip](https://github.com/KumohTaxi/Frontend/files/9792633/Troubleshooting.zip)

**Comment by GHWooo** [comment]
Has confirmed.
